AllCops:
  NewCops: enable
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - 'spec/factories/dsls/**/*'
Metrics/BlockLength:
  Exclude:
    - "**/spec/*"
  ExcludedMethods:
    - configure
    - context
    - define
    - describe
    - draw
    - factory
    - feature
    - guard
    - included
    - it
    - let
    - let!
    - scenario
    - setup
    - shared_context
    - shared_examples
    - shared_examples_for
    - transaction

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 200
  # Ignores annotate output
  AllowedPatterns: ['\A# \*\*']
  IgnoreCopDirectives: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Style/BlockComments:
  Enabled: false
  Include:
    - "**/spec/*"

# Style/ExponentialNotation
# Style/HashEachMethods
# Style/HashTransformKeys
# Style/HashTransformValues
# Style/RedundantFetchBlock
# Style/RedundantRegexpCharacterClass
# Style/RedundantRegexpEscape
# Style/SlicingWithRange

# inherit_from: .rubocop_todo.yml



# The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
#  - Layout/EmptyLinesAroundAttributeAccessor (0.83)
#  - Layout/SpaceAroundMethodCallOperator (0.82)
#  - Lint/DeprecatedOpenSSLConstant (0.84)
#  - Lint/MixedRegexpCaptureTypes (0.85)
#  - Lint/RaiseException (0.81)
#  - Lint/StructNewOverride (0.81)
# For more information: https://docs.rubocop.org/rubocop/versioning.html
