KDsl.blueprint :{{snake name}} do
  microapp     = import(:{{settings.name}}, :microapp)

  is_bundle_gem        = 1
  is_bundle_setup      = 0
  is_bootstrap         = 0
  is_customisations    = 0

  settings do
    name                parent.key
    type                parent.type
    template_rel_path   microapp.settings.template_rel_path
    description         microapp.settings.description
  end

  instructions :bundle_setup do
    fields [:template_name, f(:output, '$TEMPLATE_NAME$'), f(:command, 'generate'), f(:active, true), f(:conflict, 'overwrite'), f(:after_write, '')]

    row '.gitignore'

    row 'bin/k'
    row 'bin/khotfix'
    row 'bin/kgitsync'

    row 'hooks/pre-commit'
    row 'hooks/update-version'

    row 'bin/runonce/common.sh'
    row 'bin/runonce/setup-chmod.sh', command: 'execute'
    row 'bin/runonce/setup-git.sh', command: 'execute'
  end

  instructions :bootstrap_cmdlet do
    fields [:template_name, f(:output, '$TEMPLATE_NAME$'), f(:command, 'generate'), f(:active, true), f(:conflict, 'overwrite'), f(:after_write, '')]

    # ADD EXE (executable)
    row 'exe/cmdlet_name', 'exe/{{settings.application}}'

    # ADD EXT (extensions)
    row 'ext/cmdlet_name/cmdlet_name.c', 'ext/{{settings.application}}/{{settings.application}}.c'
    row 'ext/cmdlet_name/cmdlet_name.h', 'ext/{{settings.application}}/{{settings.application}}.h'
    row 'ext/cmdlet_name/extconf.rb', 'ext/{{settings.application}}/extconf.rb'

    row 'bin/setup'
    row 'bin/console'

    # Setup CLI and command execution
    row 'lib/cmdlet_name.rb'              , 'lib/{{settings.application}}.rb'
    row 'lib/cmdlet_name/version.rb'      , 'lib/{{settings.application}}/version.rb', conflict: 'skip'
    row 'lib/cmdlet_name/cli.rb'          , 'lib/{{settings.application}}/cli.rb'
    row 'lib/cmdlet_name/app.rb'          , 'lib/{{settings.application}}/app.rb'
    row 'lib/cmdlet_name/command.rb'      , 'lib/{{settings.application}}/command.rb'

    row '.keep'                           , 'lib/{{settings.application}}/commands/.keep'
    row '.keep'                           , 'lib/{{settings.application}}/templates/.keep'

    row 'spec/spec_helper.rb'
    row 'spec/cmdlet_name_spec.rb'        , 'spec/{{settings.application}}_spec.rb'
    
    row '.rspec'
    row '.travis.yml'                     , command: 'delete', note: 'this was generated by bundle gem'
    row 'CODE_OF_CONDUCT.md'
    row 'Gemfile'
    row 'LICENSE.txt'
    row 'cmdlet_name.gemspec'               , '{{settings.application}}.gemspec'
    row 'Rakefile'
    row 'README.md'
    row 'Guardfile'
    row '.rubocop.yml'

    row 'bin/runonce/hotfix-final.sh'     , command: 'execute'
    row 'bin/runonce/setup.sh'            , after_write: 'open'

    # row '', conflict: 'compare'
  end

  instructions :custom do
    fields [:template_name, f(:output, '$TEMPLATE_NAME$'), f(:command, 'generate'), f(:active, true), f(:conflict, 'compare'), f(:after_write, 'open')]

    # row 'README.md'#, conflict: 'overwrite'
    # row '.rubocop.yml'
  end

  actions do
    if is_bundle_gem == 1
      run_command 'bundle gem --coc --test=rspec --mit {{settings.name}}', command_creates_top_folder: true
    end
    if is_bundle_setup == 1
      run_blueprint instructions: :bundle_setup , microapp: microapp
    end
    if is_bootstrap == 1
      run_blueprint instructions: :bootstrap    , microapp: microapp 
    end
    if is_customisations == 1
      run_blueprint instructions: :custom       , microapp: microapp
    end

    # write_json is_edit: true
  end
end
