KDsl.blueprint :{{snake name}} do
  microapp     = import(:{{settings.name}}, :microapp)

  is_run = 0

  settings do
    name                parent.key
    type                parent.type
    template_rel_path   'ruby-gem'
  end

  instructions do
    fields [:template_name, f(:output, '$TEMPLATE_NAME$'), f(:command, 'generate'), f(:active, true), f(:conflict, 'overwrite'), f(:after_write, '')]

    # Setup CLI and command execution
    row 'lib/applet_name.rb'              , 'lib/{{settings.application}}.rb'
    row 'lib/applet_name/version.rb'      , 'lib/{{settings.application}}/version.rb', conflict: 'skip'

    row 'spec/spec_helper.rb'
    row 'spec/applet_name_spec.rb'        , 'spec/{{settings.application}}_spec.rb'
    
    row '.rspec'
    row '.rubocop.yml'
    row '.travis.yml'                     , command: 'delete', note: 'this was generated by bundle gem'
    row 'applet_name.gemspec'             , '{{settings.application}}.gemspec'
    row 'CODE_OF_CONDUCT.md'
    row 'Gemfile'
    row 'Guardfile'
    row 'LICENSE.txt'
    row 'Rakefile'
    row 'README.md'
  end

  L.warn 'set is_run to true if you want to run the action' if is_run == 0
  actions do
    run_blueprint microapp: microapp
    # run_command 'bin/setup'
    # run_command 'bundle install'
    # run_command 'rubocop --auto-gen-config'
  end if is_run == 1
end
