AllCops:
  DisplayCopNames: true
  ExtraDetails: true

Metrics/BlockLength:
  Exclude:
    - "app/admin/*"
    - "config/routes.rb"
    - "config/routes/**/*"
    - "lib/tasks/**/*"
  ExcludedMethods:
    - configure
    - context
    - define
    - describe
    - draw
    - factory
    - feature
    - guard
    - included
    - it
    - let
    - let!
    - scenario
    - setup
    - shared_context
    - shared_examples
    - shared_examples_for
    - transaction

Layout/LineLength:
  Max: 200
  # Ignores annotate output
  IgnoredPatterns: ['\A# \*\*']
  IgnoreCopDirectives: true

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/BlockDelimiters:
  SupportedStyles:
    - line_count_based
    - braces_for_chaining

Style/ConditionalAssignment:
  Severity: warning

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $flipper

Style/GuardClause:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/SingleLineBlockParams:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/RescuedExceptionsVariableName:
  Enabled: false
