source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '{{settings.ruby_version}}'

gem 'active_material', github: 'vigetlabs/active_material'
gem 'activeadmin'
gem 'activeadmin_addons'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> {{settings.rails_version}}'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Thin as the app server
gem 'thin'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

gem 'devise'
gem 'rack-cors', require: 'rack/cors'

group :development, :test do
  gem 'annotate', require: false
  # gem 'awesome_print'
  # gem 'figaro'
  gem 'pry-byebug', require: false
  gem 'pry-rails', require: false
  gem 'table_print', require: false

  # gem 'overcommit', require: false
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rspec', require: false

  # gem 'listen', '>= 3.0.5', '< 3.2'
  # gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'rspec-rails'

  gem 'factory_bot_rails'

  gem 'guard'
  gem 'guard-rspec'
  # gem 'axe-matchers'
  # gem 'capybara'
  # gem 'capybara-inline-screenshot'
  # gem 'email_spec'
  # gem 'fakeredis'
  # gem 'percy-capybara'
  # gem 'rails-controller-testing'
  # gem 'rspec-collection_matchers'
  # gem 'rspec-rails'
  # gem 'rspec-sidekiq'
  # gem 'rspec_junit_formatter'
  # gem 'selenium-webdriver'
  # gem 'shoulda-matchers'
  # gem 'vcr'
  # gem 'webdrivers', require: false
  # gem 'webmock', require: false
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
