// <auto-generated/>

namespace {{project.application_namespace}}.Data
{
  // Warning: This file is generated, do not manually update

  using System;
  using System.Collections.Generic;

  public partial class {{camel entity.name}}
  {
    public int Id { get; set; }

    {{#if entity.columns}}
    // Common fields
    {{#each entity.columns}}
    public {{csharp_type}} {{camel name}} { get; set; }{{#if @last}}{{else}}
    {{/if}}
    {{/each}}
    {{/if}}
    {{#if entity.relations_m1}}
    // 0-1 (Foreign Key relationships)
    {{#each entity.relations_m1}}
    public {{camel reference_type}} {{camel name}} { get; set; }{{#if @last}}{{else}}
    {{/if}}
    {{/each}}
    {{/if}}

    {{#if entity.relations_1m}}
    // 1-Many relations
    {{#each entity.relations_1m}}
    public List<{{camel reference_type}}> {{camel name_plural}} { get; set; }{{#if @last}}{{else}}
    {{/if}}
    {{/each}}
    {{/if}}
  }
}
