source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '{{settings.ruby_version}}'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> {{settings.rails_version}}'
