#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)
require '{{snake microapp.microapp.settings.application}}/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  {{camelU microapp.microapp.settings.application}}::CLI.start
rescue {{camelU microapp.microapp.settings.application}}::CLI::Error => e
  puts "ERROR: #{e.message}"
  exit 1
end
